services:
  server:
    build:
      context: .
      dockerfile: cmd/server/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SERVER_ADDR=${SERVER_ADDR:-0.0.0.0:8080}
    volumes:
      - ./.env:/app/.env
      - ./public:/app/public

  client:
    build:
      context: .
      dockerfile: cmd/client/Dockerfile
    environment:
      - WS_URL=${WS_URL:-ws://server:8080/ws}
    depends_on:
      - server
    tty: true
    stdin_open: true
    volumes:
      - ./.env:/app/.env