services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SERVER_ADDR=${SERVER_ADDR} # Передаем переменную из .env
    volumes:
      - ./.env:/app/.env # Монтируем .env файл

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      - WS_URL=${WS_URL} # Передаем переменную из .env
    depends_on:
      - server
    tty: true
    volumes:
      - ./.env:/app/.env # Монтируем .env файл